const AIExplainer = ({
  text,
  footer = 'Generated by Gemini · Not financial advice',
  onRegenerate,
  loading = false,
}) => (
  <section className="rounded-xl border border-[#374151] bg-[#111827] p-5">
    <div className="mb-4 flex items-center gap-3">
      <span className="h-2 w-2 rounded-full bg-[#10B981] animate-pulse" />
      <span className="text-sm font-semibold text-[#10B981]">AI Explainer</span>
      <span className="mx-1 h-4 border-l border-[#374151]" />
      <span className="font-mono text-xs text-[#6B7280]">Powered by Gemini 1.5 Flash</span>
    </div>
    <p className="text-sm leading-relaxed text-[#9CA3AF]">{text}</p>
    <div className="mt-4 flex items-center justify-between border-t border-[#374151] pt-3">
      <span className="font-mono text-xs text-[#6B7280]">{footer}</span>
      {onRegenerate ? (
        <button
          onClick={onRegenerate}
          disabled={loading}
          className="cursor-pointer rounded-lg border border-[#374151] px-3 py-1 text-xs text-[#9CA3AF] hover:bg-[#1F2937] disabled:cursor-not-allowed disabled:opacity-60"
        >
          {loading ? 'Generating...' : 'Regenerate'}
        </button>
      ) : null}
    </div>
  </section>
);

export default AIExplainer;
